name: Deploy to EC2

on:
  push:
    branches:
      - main      # triggers on push to main branch
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # Save private key and set permissions
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Verify key format
        if ! grep -q "BEGIN.*PRIVATE KEY" private_key; then
          echo "Error: Invalid private key format"
          exit 1
        fi
        
        # Test SSH connection
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i private_key ${USER}@${HOST} 'echo "SSH connection successful"'
        
        # Deploy
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          # Navigate to your app directory
          cd ~/nagar-nigam-freelance-backend &&
          
          # Pull latest changes
          git pull origin main &&
          
          # Install dependencies
          npm install &&
          
          # Restart PM2 process
          pm2 restart backend &&
          
          echo "Deployment completed successfully!"
        '